mysite/food/urls.py
from django.urls import path
from . import views

app_name = "food"
urlpatterns = [
    # /food/
    path("", views.IndexClassView.as_view(), name="index"),
    # /food/1
    path("<int:pk>/", views.FoodDetail.as_view(), name="detail"),
    path("item/", views.item, name="item"),
    # add items
    path("add", views.CreateItem.as_view(), name="create_item"),
    # edit items
    path("update/<int:id>/", views.update_item, name="update_item"),
    # delete items
    path("delete/<int:id>/", views.delete_item, name="delete_item")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path("login/", authentication_views.LoginView.as_view(
        template_name="user/login.html"), name="login"),
    path("logout/", authentication_views.LogoutView.as_view(
        template_name="user/logout.html"), name="logout"),
    path("profile/", user_views.profilepage, name="profile")
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://www.happyeater.com/images/default-food-image.jpg")

    def __str__(self) -> str:
        return self.item_name

    # Redirect to the detail page when the item is created
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.jpg",
                              upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.get_username()

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name","item_desc","item_price","item_image"]

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {"item_list": item_list}
    return render(request, "index.html", context)


class IndexClassView(ListView):
    model = Item
    template_name = "index.html"
    context_object_name = "item_list"


def item(request):
    return HttpResponse("This is an item view")


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {"item": item, }
    return render(request, "detail.html", context)


class FoodDetail(DetailView):
    model = Item
    template_name = "detail.html"


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("food:index")
    return render(request, "item-form.html", {"form": form})


class CreateItem(CreateView):
    model = Item
    fields = ["item_name", "item_desc", "item_price", "item_image"]
    template_name = "item-form.html"

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")

    return render(request, "item-form.html", {"form": form, "item": item})


def delete_item(request, id):
    print("delete1")
    item = Item.objects.get(id=id)
    if request.method == "POST":
        print("delete2")
        item.delete()
        print("delete3")
        return redirect("food:index")
    return render(request, "item-delete.html", {"item": item})

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(
                request, f"Welcome {username}, your account is created")
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, "user/register.html", {"form": form})


@login_required
def profilepage(request):
    return render(request, "user/profile.html")

mysite/food/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'food:index' %}">FoodApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="mr-sm-2" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Delete Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">View Item</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profile' %}">{{user.username}}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {% endif%}
            </ul>
          </div>
        </div>
      </nav>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            {{message}}
          </div>
        {% endfor%}
      {% endif %}
      {% block body%}
      {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

mysite/food/templates/detail.html
{% extends "base.html" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="{{item.item_image}}" class="card img-fluid">
            </div>
            <div class="col-md-6">
                <h1>{{object.item_name.title}}</h1>
                <h2>{{object.item_desc}}</h2>
                <h3>{{object.item_price}}</h3>
                <h4>{{object.user_name}}</h4>
                <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
{% endblock %}

mysite/food/templates/index.html
{% extends "base.html" %}

{% block body %}
    {% for item in item_list %}
    <div class="row">
        <div class="col-md-4 offset-md-1">
            <img src={{item.item_image}} class="card img-fluid" />
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>${{item.item_price}}</h6>
            <h6>{{item.user_name}}</h6>
        </div>
        <div class="col-md-3">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            <a href="{% url 'food:update_item' item.id %}" class="btn btn-success">Edit</a>

        </div>
    </div>

    {% endfor %}

    <!-- {% for item in item_list %}
    <ul>
        <li>
            <a href="{% url 'food:detail' item.id %}">{{item.id}} -- {{item.item_name}}</a>
        </li>
    </ul>
    {% endfor %} -->
{% endblock %}

mysite/food/templates/item-delete.html
{% extends "base.html" %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <h2 class="text-center display-5">Are you sure you want to delete {{item.item_name}} ?</h2>
    <div class="text-center">
        <button type="submit" class="btn btn-danger">Confirm</button>
    </div> 
</form>
{% endblock %}

mysite/food/templates/item-form.html
{% extends "base.html" %}

{% block body%}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info">
                        <div class="card-title text-white">
                            Add Item
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{field.name.title}}
                                    {{field}}
                                </div>
                                <br>
                            {% endfor %}
                            <button class="btn btn-info" type="submit">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/user/login.html
{% extends "base.html" %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title text-white">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{field.name.title}}
                                {{field}}
                            </div>
                            <br>
                        {% endfor %}
                        <button class="btn btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mysite/users/templates/user/logout.html
{% extends "base.html" %}
{% block body %}
    <h1>Your have been logged out</h1>
{% endblock %}

mysite/users/templates/user/profile.html
<h1>{{user.username}}</h1>
<img height="100px" width="100px" src="{{user.profile.image.url}}">

mysite/users/templates/user/register.html
{% extends "base.html" %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info">
                        <div class="card-title text-white">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{field.name}}
                                    <br>
                                    {{field}}
                                </div>
                            {% endfor%}
                            <br>
                            <button class="btn btn-info" type="submit">Signup</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock%}